### ISSUE TITLE
Improve the WEB API exposure

### ISSUE THREAD

**Issue by bsvin33t** [sephora-sea/static-data-engine#1]
Hey @KernCheh Instead of doing something like `query=test_attribute:foo` , don't you think doing something like  `{'query': ['test_attribute': 'foo'], 'dataset': 'test_data'}` be much better ? Also, I don't think the intension of the web api is going to be access thru the browser, as it responds back with a JSON.

**Comment by KernCheh** [comment]
@bsvin33t Thanks! will look into it

**Comment by bsvin33t** [comment]
cleanup
